scala_binary(
    name = "example_scalding_job1",
    srcs = ["Job1.scala"],
    visibility = ["//visibility:public"],
    main_class = "example_scalding.Job1",
    deps = [
             "@apache_commons_cli//jar"
           , "@apache_commons_collections//jar"
           , "@apache_commons_logging//jar"
           , "@cascading_core_jar//jar"
           , "@cascading_local_jar//jar"
           , "@cascading_hadoop_jar//jar"
           , "@guava//jar"
           , "@kryo//jar"
           , "@hadoop_common//jar"
           , "@twitter_algebird_core_jar//jar"
           , "@twitter_bijection_core_jar//jar"
           , "@twitter_chill_algebird_jar//jar"
           , "@twitter_chill_hadoop_jar//jar"
           , "@twitter_chill_jar//jar"
           , "@twitter_chill_java_jar//jar"
           , "@twitter_scalding_args_jar//jar"
           , "@twitter_scalding_core_jar//jar"
           , "@twitter_scalding_date_jar//jar"
           , "@twitter_scalding_serialization_jar//jar"
           ]
)
