load("//tools/build_rules/scalding:scalding.bzl", "scalding_binary")

scalding_binary(
    name = "example_scalding_job1",
    srcs = ["Job1.scala"],
    visibility = ["//visibility:public"],
    main_class = "example_scalding.Job1")
